from app.dicts.cargos import CARGO_KINDS
from app.dicts.vehicles import (
    ADR_CLASSES,
    BODY_COMPATIBILITY,
    BODY_TYPE_ALIASES,
    LEGACY_BODY_KIND,
    LOADING_OPTION_TO_TYPE,
    LOADING_TYPE_ALIASES,
    LOADING_TYPES,
    TEMP_VEHICLE_KINDS,
    VEHICLE_KINDS,
    VEHICLE_OPTIONS,
)

__all__ = [
    "VEHICLE_KINDS",
    "LOADING_TYPES",
    "VEHICLE_OPTIONS",
    "ADR_CLASSES",
    "CARGO_KINDS",
    "BODY_TYPE_ALIASES",
    "LEGACY_BODY_KIND",
    "LOADING_TYPE_ALIASES",
    "LOADING_OPTION_TO_TYPE",
    "BODY_COMPATIBILITY",
    "TEMP_VEHICLE_KINDS",
]
